ALTER TABLE original_tweets
  DROP COLUMN IF EXISTS technology,
  DROP COLUMN IF EXISTS business,
  DROP COLUMN IF EXISTS staff_picks,
  DROP COLUMN IF EXISTS gaming,
  DROP COLUMN IF EXISTS entertainment,
  DROP COLUMN IF EXISTS food_drink,
  DROP COLUMN IF EXISTS art_design,
  DROP COLUMN IF EXISTS news,
  DROP COLUMN IF EXISTS health,
  DROP COLUMN IF EXISTS science,
  DROP COLUMN IF EXISTS nba,
  DROP COLUMN IF EXISTS funny,
  DROP COLUMN IF EXISTS photography,
  DROP COLUMN IF EXISTS twitter,
  DROP COLUMN IF EXISTS government,
  DROP COLUMN IF EXISTS sports,
  DROP COLUMN IF EXISTS books,
  DROP COLUMN IF EXISTS travel,
  DROP COLUMN IF EXISTS music,
  DROP COLUMN IF EXISTS social_good,
  DROP COLUMN IF EXISTS faith_and_religion,
  DROP COLUMN IF EXISTS family,
  DROP COLUMN IF EXISTS television,
  DROP COLUMN IF EXISTS nascar,
  DROP COLUMN IF EXISTS fashion,
  DROP COLUMN IF EXISTS pga,
  DROP COLUMN IF EXISTS nhl,
  DROP COLUMN IF EXISTS mlb;

ALTER TABLE original_tweets
  ADD COLUMN technology         BOOLEAN DEFAULT false,
  ADD COLUMN business           BOOLEAN DEFAULT false,
  ADD COLUMN staff_picks        BOOLEAN DEFAULT false,
  ADD COLUMN gaming             BOOLEAN DEFAULT false,
  ADD COLUMN entertainment      BOOLEAN DEFAULT false,
  ADD COLUMN food_drink         BOOLEAN DEFAULT false,
  ADD COLUMN art_design         BOOLEAN DEFAULT false,
  ADD COLUMN news               BOOLEAN DEFAULT false,
  ADD COLUMN health             BOOLEAN DEFAULT false,
  ADD COLUMN science            BOOLEAN DEFAULT false,
  ADD COLUMN nba                BOOLEAN DEFAULT false,
  ADD COLUMN funny              BOOLEAN DEFAULT false,
  ADD COLUMN photography        BOOLEAN DEFAULT false,
  ADD COLUMN twitter            BOOLEAN DEFAULT false,
  ADD COLUMN government         BOOLEAN DEFAULT false,
  ADD COLUMN sports             BOOLEAN DEFAULT false,
  ADD COLUMN books              BOOLEAN DEFAULT false,
  ADD COLUMN travel             BOOLEAN DEFAULT false,
  ADD COLUMN music              BOOLEAN DEFAULT false,
  ADD COLUMN social_good        BOOLEAN DEFAULT false,
  ADD COLUMN faith_and_religion BOOLEAN DEFAULT false,
  ADD COLUMN family             BOOLEAN DEFAULT false,
  ADD COLUMN television         BOOLEAN DEFAULT false,
  ADD COLUMN nascar             BOOLEAN DEFAULT false,
  ADD COLUMN fashion            BOOLEAN DEFAULT false,
  ADD COLUMN pga                BOOLEAN DEFAULT false,
  ADD COLUMN nhl                BOOLEAN DEFAULT false,
  ADD COLUMN mlb                BOOLEAN DEFAULT false;
