COPY (
  SELECT
    ot.id,
    ot.user_id,
    ot.created_at,
    ot.created_at_day,
    ot.text,
    ot.source,
    ot.in_reply_to_status_id,
    ot.in_reply_to_user_id,
    ot.in_reply_to_screen_name,
    ot.place,
    ot.retweet_count,
    ot.favorite_count,
    ot.possibly_sensitive,
    ot.filter_level,
    ot.lang,
    ot.retweeted_status_id,
    ot.entities,
    ot.extended_entities,
    ot.geo_longitude,
    ot.geo_latitude,
    ot.has_hashtags,
    ot.has_trends,
    ot.has_urls,
    ot.has_user_mentions,
    ot.has_symbols,
    ot.has_photo,
    ot.user_ss_location,
    ot.user_ss_follower_count,
    ot.user_ss_friends_count,
    ot.user_ss_listed_count,
    ot.user_ss_statuses_count,
    ot.user_ss_utc_offset,
    ot.user_ss_time_zone,
    -- ot.category,
    ot.dead_time,
    ot.dead_time_total_retweet,

    ot.technology         AS cat_technology,
    ot.business           AS cat_business,
    ot.staff_picks        AS cat_staff_picks,
    ot.gaming             AS cat_gaming,
    ot.entertainment      AS cat_entertainment,
    ot.food_drink         AS cat_food_drink,
    ot.art_design         AS cat_art_design,
    ot.news               AS cat_news,
    ot.health             AS cat_health,
    ot.science            AS cat_science,
    ot.nba                AS cat_nba,
    ot.funny              AS cat_funny,
    ot.photography        AS cat_photography,
    ot.twitter            AS cat_twitter,
    ot.government         AS cat_government,
    ot.sports             AS cat_sports,
    ot.books              AS cat_books,
    ot.travel             AS cat_travel,
    ot.music              AS cat_music,
    ot.social_good        AS cat_social_good,
    ot.faith_and_religion AS cat_faith_and_religion,
    ot.family             AS cat_family,
    ot.television         AS cat_television,
    ot.nascar             AS cat_nascar,
    ot.fashion            AS cat_fashion,
    ot.pga                AS cat_pga,
    ot.nhl                AS cat_nhl,
    ot.mlb                AS cat_mlb,

    u.name            AS user_name,
    u.screen_name     AS user_screen_name,
    u.location        AS user_location,
    u.description     AS user_description,
    u.verified        AS user_verified,
    u.followers_count AS user_followers_count,
    u.friends_count   AS user_friends_count,
    u.listed_count    AS user_listed_count,
    u.statuses_count  AS user_statuses_count,
    u.created_at      AS user_created_at,
    EXTRACT('epoch' FROM u.created_at) AS user_created_at_unix,
    u.utc_offset      AS user_utc_offset,
    u.time_zone       AS user_time_zone,
    u.lang            AS user_lang,
    u.has_url         AS user_has_url

  FROM original_tweets ot, users u
  WHERE ot.user_id = u.id AND ot.dead_time IS NOT NULL
)
TO '/Users/daiwei/dev/class-projects/inst737/twitter-collector/csv/tweets.csv'
DELIMITER ',' CSV HEADER;
