#initialize and clean data
library(Metrics)
setwd("/Users/Wind/Desktop")
rawdata<-read.csv("tweets.csv")
data=rawdata[-c(1:3,5:23,26:27,29,34:41,47,49:67)]

#create train and test data
data_train=data[1:3000,]
data_test=data[3001:4334,]

#predict with "tweet_created_at_since_midnight"
LModel<-lm(dead_min_since_create~tweet_created_at_since_midnight,data=data_train)
LMprediction<-predict(LModel,newdata=data_test)
cor(LMprediction,data_test$dead_min_since_create)
mse(LMprediction,data_test$dead_min_since_create)
rs<-residuals(LModel)
qqnorm(rs)
qqline(rs)
LMpc<-predict(LModel,int="c",newdata=data_test)
LMpp<-predict(LModel,int="p",newdata=data_test)
plot(data_test$dead_min_since_create,data_test$tweet_create_at_since_midnight)
matlines(data_test$dead_min_since_create,LMpc)
matlines(data_test$dead_min_since_create,LMpp)

#predict with "has_hashtag"
LModel<-lm(dead_min_since_create~has_hashtags,data=data_train)
LMprediction<-predict(LModel,newdata=data_test)
cor(LMprediction,data_test$dead_min_since_create)
mse(LMprediction,data_test$dead_min_since_create)
rs<-residuals(LModel)
qqnorm(rs)
qqline(rs)
LMpc<-predict(LModel,int="c",newdata=data_test)
LMpp<-predict(LModel,int="p",newdata=data_test)
plot(data_test$dead_min_since_create,data_test$has_hashtags)
matlines(data_test$dead_min_since_create,LMpc)
matlines(data_test$dead_min_since_create,LMpp)

#predict with "has_urls"
LModel<-lm(dead_min_since_create~has_urls,data=data_train)
LMprediction<-predict(LModel,newdata=data_test)
cor(LMprediction,data_test$dead_min_since_create)
mse(LMprediction,data_test$dead_min_since_create)
rs<-residuals(LModel)
qqnorm(rs)
qqline(rs)
LMpc<-predict(LModel,int="c",newdata=data_test)
LMpp<-predict(LModel,int="p",newdata=data_test)
plot(data_test$dead_min_since_create,data_test$has_urls)
matlines(data_test$dead_min_since_create,LMpc)
matlines(data_test$dead_min_since_create,LMpp)

#predict with "has_user_mentions"
LModel<-lm(dead_min_since_create~has_user_mentions,data=data_train)
LMprediction<-predict(LModel,newdata=data_test)
cor(LMprediction,data_test$dead_min_since_create)
mse(LMprediction,data_test$dead_min_since_create)
rs<-residuals(LModel)
qqnorm(rs)
qqline(rs)
LMpc<-predict(LModel,int="c",newdata=data_test)
LMpp<-predict(LModel,int="p",newdata=data_test)
plot(data_test$dead_min_since_create,data_test$has_user_mentions)
matlines(data_test$dead_min_since_create,LMpc)
matlines(data_test$dead_min_since_create,LMpp)

#predict with "has_symbols"
LModel<-lm(dead_min_since_create~has_symbols,data=data_train)
LMprediction<-predict(LModel,newdata=data_test)
cor(LMprediction,data_test$dead_min_since_create)
mse(LMprediction,data_test$dead_min_since_create)
rs<-residuals(LModel)
qqnorm(rs)
qqline(rs)
LMpc<-predict(LModel,int="c",newdata=data_test)
LMpp<-predict(LModel,int="p",newdata=data_test)
plot(data_test$dead_min_since_create,data_test$has_symbols)
matlines(data_test$dead_min_since_create,LMpc)
matlines(data_test$dead_min_since_create,LMpp)

#predict with "has_photo"
LModel<-lm(dead_min_since_create~has_photo,data=data_train)
LMprediction<-predict(LModel,newdata=data_test)
cor(LMprediction,data_test$dead_min_since_create)
mse(LMprediction,data_test$dead_min_since_create)
rs<-residuals(LModel)
qqnorm(rs)
qqline(rs)
LMpc<-predict(LModel,int="c",newdata=data_test)
LMpp<-predict(LModel,int="p",newdata=data_test)
plot(data_test$dead_min_since_create,data_test$has_photo)
matlines(data_test$dead_min_since_create,LMpc)
matlines(data_test$dead_min_since_create,LMpp)

#predict with "user_verified"
LModel<-lm(dead_min_since_create~user_verified,data=data_train)
LMprediction<-predict(LModel,newdata=data_test)
cor(LMprediction,data_test$dead_min_since_create)
mse(LMprediction,data_test$dead_min_since_create)
rs<-residuals(LModel)
qqnorm(rs)
qqline(rs)
LMpc<-predict(LModel,int="c",newdata=data_test)
LMpp<-predict(LModel,int="p",newdata=data_test)
plot(data_test$dead_min_since_create,data_test$user_verified)
matlines(data_test$dead_min_since_create,LMpc)
matlines(data_test$dead_min_since_create,LMpp)

#predict with "user_followers_count"
LModel<-lm(dead_min_since_create~user_followers_count,data=data_train)
LMprediction<-predict(LModel,newdata=data_test)
cor(LMprediction,data_test$dead_min_since_create)
mse(LMprediction,data_test$dead_min_since_create)
rs<-residuals(LModel)
qqnorm(rs)
qqline(rs)
LMpc<-predict(LModel,int="c",newdata=data_test)
LMpp<-predict(LModel,int="p",newdata=data_test)
plot(data_test$dead_min_since_create,data_test$user_followers_count)
matlines(data_test$dead_min_since_create,LMpc)
matlines(data_test$dead_min_since_create,LMpp)

#predict with "user_friends_count"
LModel<-lm(dead_min_since_create~user_friends_count,data=data_train)
LMprediction<-predict(LModel,newdata=data_test)
cor(LMprediction,data_test$dead_min_since_create)
mse(LMprediction,data_test$dead_min_since_create)
rs<-residuals(LModel)
qqnorm(rs)
qqline(rs)
LMpc<-predict(LModel,int="c",newdata=data_test)
LMpp<-predict(LModel,int="p",newdata=data_test)
plot(data_test$dead_min_since_create,data_test$user_friends_count)
matlines(data_test$dead_min_since_create,LMpc)
matlines(data_test$dead_min_since_create,LMpp)

#predict with "user_listed_count"
LModel<-lm(dead_min_since_create~user_listed_count,data=data_train)
LMprediction<-predict(LModel,newdata=data_test)
cor(LMprediction,data_test$dead_min_since_create)
mse(LMprediction,data_test$dead_min_since_create)
rs<-residuals(LModel)
qqnorm(rs)
qqline(rs)
LMpc<-predict(LModel,int="c",newdata=data_test)
LMpp<-predict(LModel,int="p",newdata=data_test)
plot(data_test$dead_min_since_create,data_test$user_listed_count)
matlines(data_test$dead_min_since_create,LMpc)
matlines(data_test$dead_min_since_create,LMpp)

#predict with "user_statuses_count"
LModel<-lm(dead_min_since_create~user_statuses_count,data=data_train)
LMprediction<-predict(LModel,newdata=data_test)
cor(LMprediction,data_test$dead_min_since_create)
mse(LMprediction,data_test$dead_min_since_create)
rs<-residuals(LModel)
qqnorm(rs)
qqline(rs)
LMpc<-predict(LModel,int="c",newdata=data_test)
LMpp<-predict(LModel,int="p",newdata=data_test)
plot(data_test$dead_min_since_create,data_test$user_statuses_count)
matlines(data_test$dead_min_since_create,LMpc)
matlines(data_test$dead_min_since_create,LMpp)

#predict with "user_created_at_unix"
LModel<-lm(dead_min_since_create~user_created_at_unix,data=data_train)
LMprediction<-predict(LModel,newdata=data_test)
cor(LMprediction,data_test$dead_min_since_create)
mse(LMprediction,data_test$dead_min_since_create)
rs<-residuals(LModel)
qqnorm(rs)
qqline(rs)
LMpc<-predict(LModel,int="c",newdata=data_test)
LMpp<-predict(LModel,int="p",newdata=data_test)
plot(data_test$dead_min_since_create,data_test$user_created_at_unix)
matlines(data_test$dead_min_since_create,LMpc)
matlines(data_test$dead_min_since_create,LMpp)

#mutivariable prediction
library(glmnet)
LModel<-lm(dead_min_since_create~.,data=data_train)
LMprediction<-predict(LModel,newdata=data_test)
cor(LMprediction,data_test$dead_min_since_create)
mse(LMprediction,data_test$dead_min_since_create)
RLModel.fit<-cv.glmnet(as.matrix(data_train[,-(3:9)]),as.vector(data_train$dead_min_since_create),alpha=1)
plot(RLModel.fit)
coef(RLModel.fit)
Rprediction<-predict(RLModel.fit,newx=as.matrix(data_test[,-(3:9)]))
cor(Rprediction,as.vector(data_test$dead_min_since_create))

